---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cainjector-webhook-cert
  namespace: cert-manager
spec:
  secretName: cainjector-webhook-cert
  dnsNames:
    - cainjector.cert-manager.svc
    - cainjector.cert-manager.svc.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer