---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cainjector
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/cainjector-webhook-cert
webhooks:
  - name: cainjector.lestak.sh
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        namespace: cert-manager
        name: cainjector
        path: "/mutate"
        port: 8443
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None