---
apiVersion: v1
kind: Service
metadata:
  name: cainjector
  namespace: cert-manager
  labels:
    app: cainjector
    app.kubernetes.io/instance: cainjector
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: cainjector
    app.kubernetes.io/instance: cainjector